package com.alura.aluraAPI.dtos.content.insert;

import com.alura.aluraAPI.models.content.VideoLesson;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public record VideoLessonDTO(@Schema(description = "Value generated by DataBase")
                             @JsonIgnore Long id,
                             @NotBlank(message = "Required field")
                             @Schema(description = "Name video lesson")
                             @Size(max = 80, message = "Maximum of 80 characters") String nameLesson,
                             @NotBlank(message = "Required field")
                             @Schema(description = "Url for video lesson")
                             String archive,
                             @Schema(description = "Duration in minutes")
                             Integer duration) {
    public VideoLessonDTO(VideoLesson x) {
        this(x.getId(), x.getNameLesson(), x.getArchive(), x.getDuration());
    }
}
